apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: /mnt/nfs_share
    server: 10.0.0.1
  storageClassName: nfs
  volumeMode: Filesystem
