apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-logs-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: /mnt/nfs_share
    server: 10.0.0.1
  storageClassName: nfs
  volumeMode: Filesystem
  claimRef:
    name: gitlab-logs-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-data-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: /mnt/nfs_share
    server: 10.0.0.1
  storageClassName: nfs
  volumeMode: Filesystem
  claimRef:
    name: gitlab-data-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-config-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: /mnt/nfs_share
    server: 10.0.0.1
  storageClassName: nfs
  volumeMode: Filesystem
  claimRef:
    name: gitlab-config-pvc
