apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
  volumeName: gitlab-data-pv
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-config-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
  volumeName: gitlab-config-pv
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-logs-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
  volumeName: gitlab-logs-pv
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce
        securityContext:
          runAsUser: 0
          allowPrivilegeEscalation: true
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/gitlab
          name: gitlab-config
          readOnly: false
        - mountPath: /var/log/gitlab
          name: gitlab-logs
          readOnly: false
        - mountPath: /var/opt/gitlab
          name: gitlab-data
          readOnly: false
      volumes:
      - name: gitlab-config
        persistentVolumeClaim:
          claimName: gitlab-config-pvc
      - name: gitlab-logs
        persistentVolumeClaim:
          claimName: gitlab-logs-pvc
      - name: gitlab-data
        persistentVolumeClaim:
          claimName: gitlab-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  type: NodePort
  selector:
    app: gitlab
  ports:
    - port: 14563
      targetPort: 80
      name: gitlab
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - gitlab.mclermont.ca
    secretName: gitlab
  rules:
  - host: gitlab.mclermont.ca
    http:
      paths:
      - path: '/'
        pathType: Prefix
        backend:
          service:
            name: gitlab
            port:
              number: 14563
