apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-logs-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: /mnt/nfs_share/gitlab/logs
    server: 10.0.0.1
  storageClassName: nfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-data-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: /mnt/nfs_share/gitlab/data
    server: 10.0.0.1
  storageClassName: nfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-config-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: /mnt/nfs_share/gitlab/config
    server: 10.0.0.1
  storageClassName: nfs
  volumeMode: Filesystem
